name: KrimSale
main: de.bdh.ks.Main
version: 1.0
authors: [wmchris]
permissions:
    ks.buy:
        description: User permissions for buy
        default: op
    ks.sell:
        description: User permissions for sell
        default: op
    ks.admin:
        description: User permissions for admin
        default: op
depend: [Vault]
commands:
    auction:
         description: KrimSale Command
         usage: /auction params