name: KrimSale
main: de.bdh.ks.Main
version: 1.0
authors: [wmchris]
depend: [WorldEdit]
permissions:
    ks.buy:
        description: User permissions for buy
        default: op
    ks.sell:
        description: User permissions for sell
        default: op
    ks.sign:
        description: User permissions for signs
        default: op
    ks.list:
        description: User permissions for list
        default: op
    ks.admin:
        description: User permissions for admin
        default: op
    ks.superadmin:
        description: User permissions for superadmin
        default: op
depend: [Vault]
commands:
    auction:
         description: KrimSale Command
         usage: /auction params
    ks:
         description: KrimSale Admin
         usage: /ks params